### ISSUE TITLE
KEB must create (and read from config map) overrides with proper type

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1185]
**Description**

Right now when KEB reads config maps and send them to provisoner/reconciler they are always strings. One exception is that we convert "false", "true" ones to boolean, which is a workaround implementation.

**Reasons**

Helm templating expect proper types (for example if statements in helm chart could work wrong with strings)

**AC**

0) organise a meeting with reconciler team to discuss that improvement and make sure it makes sense
1) define how configMaps should look like and how KEB consumes them to achieve the goal to pass proper types to provisioner/reconciler
2) find a nice way how to support both solutions to have zero downtime when KEB will be updated/rolled back

**Idea**
- about AC 1) all configMaps has just one key and value will be a json
- about AC 2) enchance existing configMap with new key and modify KEB to work with both ways at the same time

**Links**
- https://github.com/helm/helm/blob/main/pkg/strvals/parser.go

**Comment by a-thaler** [comment]
At the moment the Kyma CLI and also the reconciler interface itself is supporting the full expressiveness of Helm values. When designing the chart of a kyma component you can leverage that full expressiveness and can work with the yaml objects like iterating over arrays.

When it comes to KEB and the configuration management of it, you can only pass strings or booleans and configuration options in your kyma component are not manageable anymore by KEB; except you apply ugly workarounds like templating of the input and configuring the values as multi-line strings (resulting into customisations of charts when taking them from upstream like in the case of monitoring).

I would expect support for the typical types as supported by Helm values, so the regular types as defined in JSON/YAML. By managing the configuration as yaml documents you can use typical parsers and you are good to go.

So I recommend to add support for yaml documents as config input and use regular JSON type system in the API itself for logic.

A way of configuration I can imagine and which could even coexist with current settings is:

````
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-overrides
  namespace: kcp-system
  labels:
    component: monitoring
    overrides-plan-xxx: "true"
   ...
data:
# old approach
  grafana.env.GF_ALERTING_ENABLED: "false"
  grafana.extraExposePorts: |-
    - port: 15020
       targetPort: 15020
# new approach
  values.yaml: |-
    grafana:
      env:
        GF_ALERTING_ENABLED: "false"
      extraExposePorts:
         - port: 15020
            targetPort: 15020
```
Here you still label the configmap with the component name and there is a static configmap key with the related values.yaml inside.

Alternatively we could remove the component label fully and have the component name either as config map key or as in the CLI as root key in the values.yaml itself. With that we could configure multiple components with one configmap
