### ISSUE TITLE
Add `installHint` to the generated kubeconfig file

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/control-plane#1295]
**Description**

Add `installHint` to the kubeconfig file to explain how to get the required `oidc-plugin` in order to authenticate.

**Reasons**

Kubeconfig file generated by control-plane uses an oidc-login plugin. In case users dont have it installed, the user is left w/o a clue how to preceed

**Attachments**
https://kubernetes.io/docs/reference/access-authn-authz/authentication/

**Comment by kwiatekus** [comment]
Unfortunatelly the `installHint` works on command level.
So it would show hint in case `kubect`l is not installed... not in case kubectl's `oidc-login` plugin is not present

```yaml
apiVersion: v1
kind: Config
users:
- name:myUser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login #<--- plugin
      - get-token
      command: kubectl #<--- command
      env: null
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Comment by kwiatekus** [comment]
If we want to make use of `installHint` we'd need to target `kubectl-oidc_login` plugin executable instead of kubectl executable, ie:

```yaml
users:
- name: myUser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=....
      - --oidc-client-id=...
      - --oidc-extra-scope=email
      - --oidc-extra-scope=openid
      command: kubectl-oidc_login
      env: null
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
Such setup works on MacOS, but I fear it would cause problems on other platforms
