### ISSUE TITLE
Refactor KEB to not support 1.x Kyma related steps

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1556]
**Description**

Refactor KEB to not support 1.x Kyma related steps.

**Reasons**

Those steps are obsolete and not used in the KEB provisioning flows.

**AC**

- remove obsolete 1.x steps and if needed refactor existing ones to make provisioning, deprovisioning, update and upgrade flows clean
- reduce complexity of KEB flows and code, I expected steps code will be reduced by half

**Comment by szwedm** [comment]
**Additional components collection step**

To enable the setting of additional components per Kyma version and plan we need a new approach to collect them for SKR. One solution might be declarative creation of ConfigMaps and kustomize. We already have similar working functionality for collecting runtime components overrides.

The idea
Add `additional-components.yaml` to `base` folder where overrides for specific runtime version are stored ([e.g. 2.1 base](https://github.tools.sap/kyma/management-plane-config/tree/master/resources/runtimes/2.1/base)).
Additional-components.yaml should contain ConfigMaps declarations with additional components set for plans.  
Example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-component-service-manager-proxy
  namespace: kcp-system
  labels:
    component: service-manager-proxy
    add-cmp-plan-azure: "true"
    add-cmp-plan-aws: "true"
    add-cmp-plan-openstack: "true"
    add-cmp-plan-gcp: "true"
    add-cmp-plan-azure_ha: "true"
    add-cmp-plan-aws_ha: "true"
    add-cmp-plan-preview: "true"
data:
  component.name: "service-manager-proxy"
  component.namespace: "kyma-system"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-component-sc-migration
  namespace: kcp-system
  labels:
    component: sc-migration
    add-cmp-plan-azure: "true"
    add-cmp-plan-aws: "true"
    add-cmp-plan-gcp: "true"
data:
  component.name: "service-manager-proxy"
  component.namespace: "kyma-system"
  component.source: "https://github.com/kyma-incubator/sc-removal/releases/download/0.5.1/sap-btp-operator-migration-v0.5.1.tgz"
```
`kustomization.yaml` contains runtime versions for which prepared ConfigMaps should be relevant ([kustomization.yaml in base folder for 2.1](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/runtimes/2.1/base/kustomization.yaml)).

In KEB we can provide a new type implementing [this interface](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/process/input/builder.go#L53) which would be responsible for collecting all runtime components. Additional components would be retrieved on the basis of runtime version and plan labels. Even better, we could seperate required components and additional components by providing two interfaces.

**Comment by piotrmiskiewicz** [comment]
Remove Kyma 1 support: https://github.com/piotrmiskiewicz/control-plane/tree/remove-kyma1-from-keb

**Comment by piotrmiskiewicz** [comment]
@szwedm - your idea is to have one config map per additional components, this is what I don't like.

**Comment by szwedm** [comment]
@piotrmiskiewicz - thanks for feedback.
We can provide yaml for each additional component, this way we will keep consistency in the repo like it is with components overrides.

**Comment by szwedm** [comment]
PR with new components provider:
https://github.com/kyma-project/control-plane/pull/1686

New components provider internally has two mini components providers, one for required components and the other for additional components. Required components are fetched only from the bucket associated with Kyma 2 (Kyma 1 is no longer supported). Contents from the yaml file with list of Kyma components are read and then unmarshalled to KymaComponent structs with the distinction of prerequisites. For additional components we have two scenarios, provider gets defaults from defined yaml file when there are no configmaps created for any additional component for given version and plan or overwrites the defaults when there is at least one configmap with additional component for given version and plan (similar to HTTP PUT). In biref, configmap with at least one additional component = no default list of additional components. For example the following configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    add-cmp-plan-azure: "true"
    add-cmp-version-2.2.0: "true"
    component: test
  name: additional-component-test-2.2
  namespace: kcp-system
data:
  component.name: test
  component.namespace: test-namespace
```
will cause the provider to include only this one `test` additional component in the additional components list for Kyma 2.2.0 and azure plan.
