### ISSUE TITLE
KEB: Support additional component per version and plan

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1824]
**Description**

Let's provide concept and implementation that we can easily change additional components list per Kyma version. Then going further lets allow to provide that list even for version + plan.

**Reasons**

Right now we can set additional components globally. That means for example if new Kyma version will not want to have some additional component then we cannot achieve that.

**Acceptance Criteria**
1) Prepare examples that will show we can achieve requirements in easy and understandable way (leave them in the comment under this ticket)
1.1) prepare example configuration files where all Kyma versions and plans has the same list of AddCom (include change in kcp.yaml too)
1.2) prepare example configuration files where since 2.4 Kyma version we have new AddCom list
1.3) prepare example configuration files where since 2.4 Kyma version we have new AddCom list and azure plan has different new AddCom list
1.4) prepare example configuration files where since 2.4 only azure plan has new AddCom list
1.5) prepare example configuration files where since 2.4 only azure and gcp plans have new AddCom list, and azure_lite new AddCom2
1.6) prepare example configuration files where since 2.4 trial plan has no AddCom list
2) Implement, test and document given feature

**Comment by szwedm** [comment]
Providing configuration examples as stated in:
> 1. Prepare examples that will show we can achieve requirements in easy and understandable way (leave them in the comment under this ticket)

Examples are yaml files which can be created in KCP env.
>    1.1) prepare example configuration files where all Kyma versions and plans has the same list of AddCom (include change in kcp.yaml too)
```yaml
# kcp.yaml
kyma-environment-broker.defaultAdditionalRuntimeComponents: |-
  - name: "additional-component1"
    namespace: "kyma-system"
  - name: "additional-component2"
    namespace: "test-system"
  - name: "additional-component3"
    namespace: "kyma-system"
    source:
      url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
```

>    1.2) prepare example configuration files where since 2.4 Kyma version we have new AddCom list
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  runtime-version: "2.4.0"
resources:
  - additional-components.yaml
---
# additional-components-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    additional-components-plan-default: "true"
data:
  components:
    # no additional-component1
    - name: "additional-component2"
      namespace: "test-system"
    - name: "additional-component3"
      namespace: "kyma-system"
      source:
        url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
```
>    1.3) prepare example configuration files where since 2.4 Kyma version we have new AddCom list and azure plan has different new AddCom list
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  runtime-version: "2.4.0"
resources:
  - additional-components.yaml
  - additional-components-azure.yaml
---
# additional-components-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    additional-components-plan-default: "true"
data:
  components:
    # no additional-component1
    - name: "additional-component2"
      namespace: "test-system"
    - name: "additional-component3"
      namespace: "kyma-system"
      source:
        url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
---
# additional-components-azure-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components-azure
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    # label to fetch components for azure plan only
    additional-components-plan-azure: "true"
data:
  components:
    - name: "additional-component1"
      namespace: "kyma-system"
    - name: "additional-component2"
      namespace: "test-system"
    # no additional-component3
    - name: "azure-component"
      namespace: "azure-system"
      source:
        url: "https://azure.domain/component/azure-component.git"
```
>    1.4) prepare example configuration files where since 2.4 only azure plan has new AddCom list
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  runtime-version: "2.4.0"
resources:
  - additional-components-azure.yaml
---
# additional-components-azure-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components-azure
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    # label to fetch components for azure plan only
    additional-components-plan-azure: "true"
data:
  components:
    - name: "additional-component1"
      namespace: "kyma-system"
    - name: "additional-component2"
      namespace: "test-system"
    # no additional-component3
    - name: "azure-component"
      namespace: "azure-system"
      source:
        url: "https://azure.domain/component/azure-component.git"

```
>    1.5) prepare example configuration files where since 2.4 only azure and gcp plans have new AddCom list, and azure_lite new AddCom2
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  runtime-version: "2.4.0"
resources:
  - additional-components-azure-gcp.yaml
  - additional-components-azure-lite.yaml
---
# additional-components-azure-gcp-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components-azure-gcp
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    additional-components-plan-azure: "true"
    additional-components-plan-gcp: "true"
data:
  components:
    - name: "additional-component1"
      namespace: "kyma-system"
    # no additional-component2
    - name: "additional-component3"
      namespace: "kyma-system"
      source:
        url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
    - name: "azure-gcp-component"
      namespace: "kyma-system"
      source:
        url: "https://azure.gcp.domain/component/azure-gcp-component.git"
---
# additional-components-azure-lite-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components-azure-lite
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    # label to fetch components for azure_lite plan only
    additional-components-plan-azure-lite: "true"
data:
  components:
    - name: "additional-component1"
      namespace: "kyma-system"
    # no additional-component2
    # no additional-component3
    - name: "azure-lite-component"
      namespace: "lite-system"
      source:
        url: "https://azure-lite.domain/component/azure-lite-component.git"

```
>    1.6) prepare example configuration files where since 2.4 trial plan has no AddCom list
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  runtime-version: "2.4.0"
resources:
  - additional-components-trial.yaml
---
# additional-components-trial-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-components-trial
  namespace: kcp-system
  labels:
    # one option for clarity
    runtime-version-2.4.0: "true"
    # label to fetch components for trial plan only
    additional-components-plan-trial: "true"
data:
  components:
    # no components
```

**Comment by szwedm** [comment]
After presenting the examples we agreed that kcp.yaml should stay clear of additional components. Furthermore we would like to have one ConfigMap which should contain different configurations for given version and plan:
```yaml
---
# runtimes/2.4/base/kustomization.yaml // only DELTA
commonLabels:
  runtime-version-2.4.0: "true"
  # OR
  overrides-version-2.4.0: "true"
resources:
  - keb-config.yaml
---
# keb-config-2.4.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keb-config
  namespace: kcp-system
  labels:
    keb-config: "true"
    overrides-version-2.4.0: "true"
data:
  config:
    - plan: "default"
      additional-components:
      - name: "additional-component1"
        namespace: "kyma-system"
      - name: "additional-component2"
        namespace: "test-system"
      - name: "additional-component3"
        namespace: "kyma-system"
        source:
          url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
    - plan: "azure"
      additional-components:
      - name: "additional-component1"
        namespace: "kyma-system"
      - name: "additional-component2"
        namespace: "test-system"
      # no additional-component3
      - name: "azure-component"
        namespace: "azure-system"
        source:
          url: "https://azure.domain/component/azure-component.git"
    - plan: "gcp"
      additional-components:
      - name: "additional-component1"
        namespace: "kyma-system"
      # no additional-component2
      - name: "additional-component3"
        namespace: "kyma-system"
        source:
          url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
      - name: "gcp-component"
        namespace: "kyma-system"
        source:
          url: "https://gcp.domain/component/gcp-component.git"
    - plan: "trial"
      additional-components:
        # no components

```

**Comment by szwedm** [comment]
# Kyma Environment Broker configuration for given runtime version and plan  
We will store KEB configuration in a configmap which should be created when new runtime version is released. It should be stored along `kustomization.yaml` in the `base` folder what will allow `kustomize` to apply label with runtime version 
to the configmap. The correct configuration will be selected on the basis of labels, one label for identifying KEB configuration file and one label for identifying runtime version. For determining runtime version we can use the label which works for overrides collection mechanism:
```yaml
overrides-version-2.4.0: "true"
```
or define a new one, like:  
```yaml
runtime-version-2.4.0: "true"
```
Below is an example of how `kustomization.yaml` could look like:
```yaml
# base/kustomization.yaml
nameSuffix: "-2.4"
namespace: kcp-system
commonLabels:
  runtime-version-2.4.0: "true"
resources:
  - keb-config.yaml
```
Configuration for KEB should be centered around available plans and 
stored in `data` field in `keb-config.yaml` configmap. `data` field represents a `map[string]string` ([ref](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/)). 
Plan names should be the keys of the map in which configuration for given plan is a value for given key. 
See example below:
```yaml
# base/keb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keb-config
  namespace: kcp-system
  labels:
    keb-config: "true"
data:
  default: |-
    foo: "bar"
    oidc:
      clientID: "12345"
      issuerURL: "https://default.issuer.local"
    upgradeVersion: "2.5.0"
    additional-components:
      - name: "additional-component1"
        namespace: "kyma-system"
      - name: "additional-component2"
        namespace: "test-system"
  azure: |-
    oidc:
      clientID: "6789"
      issuerURL: "https://azure.issuer.local"
    upgradeVersion: "2.4.4"
    additional-components:
      - name: "additional-component3"
        namespace: "kyma-system"
      - name: "azure-component"
        namespace: "azure-system"
        source:
          url: "https://azure.domain/component/azure-component.git"
  gcp: |-
    oidc:
      clientID: "9876"
      issuerURL: "https://gcp.issuer.local"
    additional-components:
      - name: "additional-component3"
        namespace: "kyma-system"
        source:
          url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
      - name: "gcp-component"
        namespace: "kyma-system"
        source:
          url: "https://gcp.domain/component/gcp-component.git"
  trial: |-
    additional-components:    
  # no components
```
To add a configuration for a new plan it is required to add a new entry to the map. Configuration can contain required and optional fields and should be validated. KEB should fetch configuration by searching for `runtime-version-2.4.0` and `keb-config` labels and unmarshall it to the appropriate struct.

**Comment by szwedm** [comment]
### Additional components
Additional components is the first configuration entry we would like to open for customization. `additional-components` should be a required field where empty value is allowed. Empty value means that a runtime provisioned with the given plan should not contain any additional component. Example: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keb-config
  namespace: kcp-system
  labels:
    keb-config: "true"
data:
  trial: |-
    additional-components:
# no additional components
```
To expand the configuration with additional components for some other plan, e.g. `gcp`, 
it is required to provide `gcp` entry with explicitly defined additional components to the `data` map:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keb-config
  namespace: kcp-system
  labels:
    keb-config: "true"
data:
  trial: |-
    additional-components:
# no additional components
  gcp: |-
    additional-components:
      - name: "additional-component3"
        namespace: "kyma-system"
        source:
          url: "https://test.local/artifacts/additional-component3-0.0.1.tgz"
      - name: "gcp-component"
        namespace: "kyma-system"
        source:
          url: "https://gcp.domain/component/gcp-component.git"
```
