### ISSUE TITLE
[Gardener] Static service account token Secrets deprecation

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2763]
We get the following message in our CronJobs:
```
you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details
```

This is used in, e.g.:
- envCleanupJob
- maybe skr-test
- ... 

**AC**
- convert to the new way supported by Gardener

**Comment by jaroslaw-pieszka** [comment]
According to direct communication with SRE:
`gardener-credentials` secret containing token to access `compass-provisioner` service account
is rotated by SRE using a Jenkins job (triggered every 6 weeks). This rotation issues token valid for 90 days.
The rotation is compliant, it's done by another service account. compass-provision doesn't have permission to rotate it's own key.

**Comment by jaroslaw-pieszka** [comment]
In SKR tests we use kubeconfig referred by environment variable GARDENER_KYMA_PROW_KUBECONFIG:
    env:
```
- name: GARDENER_KYMA_PROW_KUBECONFIG
        value: /etc/credentials/gardener-kyma-prow/kubeconfig
...
    volumes:
      - name: gardener-kyma-prow-kubeconfig
        secret:
          secretName: gardener-kyma-prow-kubeconfig
```
This secret is rotated daily.
