### ISSUE TITLE
KEB: Allow specifing private IP address range when provisiong Kyma runtime

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2942]
**Description**
When that will be supported by the Provisioner, the KEB needs to expose such an option for users. This is only exposed when a user creates a cluster. Updates are not allowed.

**AC**
- [x] 1) Use API from provisioner (ticket: https://github.com/kyma-project/control-plane/issues/2946)
  - [x] a) contact frogs and leave your feedback about their API design, check how new API validates new inputs
  - [x] b) PB suggested that one additional field will be required to narrow down ranges, check with frogs
 PR: https://github.com/kyma-project/control-plane/pull/3020
- [x] 2) Adjust schema with new input parameter for SKR creation (only creation input parameters)
  - affected plans:
    - aws, OpenStack, free, gcp, azure, azure_lite
  - all new params under `networking` section (same like `oidc` parameters)
- [x] 3) check how we can validate input in the schema itself
- [x] 4) In case of wrong input params values, return failure for this SKR with proper message
- [x] 5) Add new skr-test scenario with `networking` params in use

**Links**
- https://gardener.cloud/docs/gardener/usage/shoot_networking/

**Comment by Disper** [comment]
Hiho @kyma-project/gopher,
please see [this comment](https://github.com/kyma-project/control-plane/issues/2946#issuecomment-1674290867) regarding API proposal. Looking forward to your feedback.

Regarding the part:
>check how new API validates new inputs

We're relying on the gardener validation that is implemented [here](https://github.com/gardener/gardener/blob/4f853e308500f57cad5c881227307fbc865736d5/pkg/utils/validation/cidr/cidr.go).

<details>
  <summary>Example validation - must be valid canonical CIDR </summary>
  
  ``` 
  "message": "Failed to start provisioning, error creating Shoot for fbb1effd-99d9-4dd3-8bf6-89b639b4ecf4 cluster: %!!(MISSING)!(MISSING)s(MISSING), Shoot.core.gardener.cloud \"md-aws-cidr\" is invalid: [spec.networking.pods: Invalid value: \"10.250.0.1/19\": must be valid canonical CIDR, spec.networking.services: Invalid value: \"10.250.0.2/19\": must be valid canonical CIDR]",
  ```
</details>

<details>
  <summary>Example validation - must not overlap </summary>

   ``` 
"message": "Failed to start provisioning, error creating Shoot for 37c5736a-07f7-479a-93ad-a8ba57d70066 cluster: %!!(MISSING)!(MISSING)s(MISSING), admission webhook \"validation.aws.provider.extensions.gardener.cloud\" denied the request: [networking.pods: Invalid value: \"10.250.0.0/19\": must not overlap with \"networks.vpc.cidr\" (\"10.250.0.0/16\"), networking.services: Invalid value: \"10.250.0.0/19\": must not overlap with \"networks.vpc.cidr\" (\"10.250.0.0/16\"), networks.zones[0].workers: Invalid value: \"10.250.0.0/19\": must not overlap with \"networking.pods\" (\"10.250.0.0/19\"), networks.zones[0].workers: Invalid value: \"10.250.0.0/19\": must not overlap with \"networking.services\" (\"10.250.0.0/19\")]",
  ```

</details>

**Comment by piotrmiskiewicz** [comment]
hi @pbochynski , could you elaborate 1.b

**Comment by pbochynski** [comment]
There are 2 settings in shoot:
  networking:
    nodes: 10.180.0.0/16

and
  provider:
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16

It is not required tohave such big  IP ranges. 10.180.0.0/25 should be sufficient. It will allow us to create VPC peering easier.

**Comment by piotrmiskiewicz** [comment]
This is how IP ranges are set for AWS,GCP,AZure:


# GCP

```yaml
 networking:
   pods: 100.64.0.0/12
   nodes: 10.250.0.0/19
   services: 100.104.0.0/13

   provider:
     type: gcp
     controlPlaneConfig:
       kind: ControlPlaneConfig
       apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
       zone: us-central1-a
     infrastructureConfig:
       kind: InfrastructureConfig
       apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
       networks:
         worker: 10.250.0.0/19
         workers: 10.250.0.0/19
```

# AWS

```yaml
  networking:
    pods: 100.64.0.0/12
    nodes: 10.250.0.0/16
    services: 100.104.0.0/13
    
  provider:
    type: aws
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      cloudControllerManager:
        useCustomRouteController: true
      kind: ControlPlaneConfig
      storage:
        managedDefaultClass: true
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: us-east-1d
            internal: 10.250.48.0/20
            public: 10.250.32.0/20
            workers: 10.250.0.0/19
          - name: us-east-1a
            internal: 10.250.112.0/20
            public: 10.250.96.0/20
            workers: 10.250.64.0/19
          - name: us-east-1f
            internal: 10.250.176.0/20
            public: 10.250.160.0/20
            workers: 10.250.128.0/19
```

# Azure

```yaml
  networking:
    type: calico
    pods: 100.64.0.0/12
    nodes: 10.250.0.0/16
    services: 100.104.0.0/13

  provider:
    type: azure
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      networks:
        vnet:
          cidr: 10.250.0.0/16
        zones:
          - name: 3
            cidr: 10.250.0.0/19
            natGateway:
              enabled: true
              idleConnectionTimeoutMinutes: 4
          - name: 2
            cidr: 10.250.32.0/19
            natGateway:
              enabled: true
              idleConnectionTimeoutMinutes: 4
          - name: 1
            cidr: 10.250.64.0/19
            natGateway:
              enabled: true
              idleConnectionTimeoutMinutes: 4
```
