### ISSUE TITLE
Provisioner ShootUpgrade mutation allows for inconsistent Azure network zones setup

### ISSUE THREAD

**Issue by koala7659** [kyma-project/control-plane#3023]
**Description**

Provisioner `shootUpgrade` mutation executed on a Azure Kyma cluster may cause a situation where the real network zone setup in Gardener is not consistent with entries stored in the provisioner database. Afterwards the mutation `runtimeStatus`  will report wrongly the network setup for such a cluster.

**Scenario to reproduce**

1. Provision runtime on Azure where two  network zones are specified:

```
providerSpecificConfig: {  
                    azureConfig: { 
                        vnetCidr: "10.250.0.0/19",
                        enableNatGateway: true,
                        idleConnectionTimeoutMinutes: 4,
                        azureZones: [
                        {
                            name: 1,
                            cidr: "10.250.0.0/24"
                        },
                        {
                            name: 2,
                            cidr: "10.250.1.0/24"
                        }
                        ]
                    }
                }
```

2. Send `upgradeShoot` mutation where there is no any network zone specified

```
                providerSpecificConfig: {  
                    azureConfig: { 
                        vnetCidr: "10.250.0.0/19",
                        idleConnectionTimeoutMinutes: 4,
                    }
                }
 
```
3. Upgrade operation ends successfully. Query the cluster with `runtimeStatus` and check Azure config:

```
"providerSpecificConfig": {
                        "vnetCidr": "10.250.0.0/19",
                        "zones": null,
                        "azureZones": null,
                        "enableNatGateway": null,
                        "idleConnectionTimeoutMinutes": 4
                    }
```

4. Go to Gardener and check yaml definition for the upgraded shoot cluster. The previous network zone setup has not been changed.

```
networks:
        vnet:
          cidr: 10.250.0.0/19
        zones:
          - cidr: 10.250.0.0/24
            name: 1
            natGateway:
              enabled: true
              idleConnectionTimeoutMinutes: 4
          - cidr: 10.250.1.0/24
            name: 2
            natGateway:
              enabled: true
              idleConnectionTimeoutMinutes: 4
```
