### ISSUE TITLE
Enhance cluster provisioning to include cert & dns extentions

### ISSUE THREAD

**Issue by strekm** [kyma-project/control-plane#875]
**Description**

Add `shoot-dns-service` and `shoot-cert-service` to SKR shoot specification used for provisioning clusters. These extensions are responsible for replicating cert-management and dns-management CR to seed clusters. 

  ```yaml
  kind: Shoot
  spec:
    # ...
    # others specs
    # ...
    extensions:
        - type: shoot-dns-service
        providerConfig:
            apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
            dnsProviderReplication:
               enabled: true
            kind: DNSConfig
        - type: shoot-cert-service
        providerConfig:
            apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
            kind: CertConfig
            shootIssuers:
               enabled: true
    # ...
    # others specs
    # ...
  ```

**Reasons**

To enable SKR users to expose workloads under their domain `shoot-dns-service` and `shoot-cert-serice` extensions needs to be configured for SKR shoot cluster. 

**Attachments**
https://github.com/kyma-project/control-plane/blob/45b703461e95cef9f186dcb25434ac9827df01c4/components/provisioner/internal/model/gardener_config.go#L64
https://github.com/kyma-project/kyma/issues/5578
